nome = input('Nome completo: ')
div = nome.split()
print('Nome maiúsculo: {}.'.format(nome.upper()))
print('Nome minúsculo: {}.'.format(nome.lower()))
print(len(div[0]))
print(f'primeiro nome {len(div[0])}')
